# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  forest_env_secret: b90620cfd56001b744be807e709c770dc8d931064329cd40af9fe6a5e4a9954d
  forest_auth_secret: -XNX91_8Yfdpz0AXnuDKQA
  secret_key_base: 077b2b799e42c5453e0bad84f54819dce0bbc58ad5301292ec0c4499e5e76b3e9ee663e146149e2492cdf4134c184c3663a23712b51ce587eeb4bd120b2ac76f

test:
  secret_key_base: fce4de2c78b179c8f5749fa3184e64fc42fb6bb775296039bc6a1541e76ea400a1ac6e3fcd9e5e402df52b292f02d8f1439c5d9f3aa6e6a41be89b8971b22d20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
